# NumPy 学习笔记

## ndarray 特性
### 1. 多维性质

In [4]:
# 创建 0 维 ndarray 数组
import numpy as np
arr = np.array(5)
print(arr)
print('arr 的维度:', arr.ndim)  # 查看维度

5
arr的维度: 0


In [32]:
# 创建 1 维 ndarray 数组
arr = np.array([1, 2, 3])
print(arr)
print('arr 的维度:', arr.ndim)  # 查看维度

[1 2 3]
arr的维度: 1


In [6]:
# 创建 2 维 ndarray 数组
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('arr 的维度:', arr.ndim)  # 查看维度

[[1 2 3]
 [4 5 6]]
arr的维度: 2


### 2. 同质性

In [13]:
# 不同数据类型会被自动转换
arr = np.array([1, 1.5])
print(arr)

[1.  1.5]


## ndarray 的属性

In [17]:
# 查看数组的形状
arr = np.array(1)
print(arr)
print('数组的形状:', arr.shape)

1
数组的形状 ()


In [20]:
# 一维数组的形状
arr = np.array([1, 2, 3])
print(arr)
print('数组的形状:', arr.shape)

[1 2 3]
数组的形状 (3,)


In [ ]:
# 二维数组的形状
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状:', arr.shape)
print('数组的大小:', arr.size)  # 元素个数

[[1 2 3]
 [4 5 6]]
数组的形状 (2, 3)
6


In [36]:
# 查看数组的更多属性
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print('数组的形状:', arr.shape)
print('数组的大小:', arr.size)  # 元素个数
print('数组的数据类型:', arr.dtype)  # 数据类型
print('数组的转置:\n', arr.T)  # 转置

[[1 2 3]
 [4 5 6]
 [7 8 9]]
数组的形状 (3, 3)
9
int64
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## ndarray 数组的创建

In [43]:
# 从列表创建 ndarray 数组
list = [1, 2, 3]
arr = np.array(list, dtype=np.float64)
print(arr)
print('数组的维度:', arr.ndim)

[1. 2. 3.]
1


In [47]:
# 数组的拷贝
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


In [51]:
# 创建预定义形状的数组
# 全 0 数组
arr = np.zeros((2, 3), dtype=np.int64)
print(arr)
print('数据类型:', arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [56]:
# 一维全 0 数组
arr = np.zeros((2,), dtype=np.int64)
print(arr)

[0 0]


In [58]:
# 全 1 数组
arr = np.ones((5, 8), dtype=np.int64)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [83]:
# 未初始化数组
arr = np.empty((5, 8), dtype=np.int64)
print(arr)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [84]:
# 填充固定值的数组
arr = np.full((9, 9), 2021, dtype=np.int64)
print(arr)

[[2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]]


In [89]:
# 使用其他数组的形状创建数组
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.full_like(arr, 2026)
print(arr1)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026

In [95]:
# 等差数列
arr = np.arange(2, 11, 2)  # 不包含最后一个 11
print(arr)

[ 2  4  6  8 10]


In [111]:
# 等间隔数列
arr = np.linspace(1, 10, 5, dtype=int)  # 均分成 5 个等间隔的数
print(arr)

[ 1  3  5  7 10]


In [132]:
# 对数间隔数列
arr = np.logspace(1, 10, 10, base=2)  # 以 2 为底
print(arr)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


## NumPy 函数与数学公式对应

| 函数                          | 数学类型 | 公式/描述                  | 示例输出                  |
|-------------------------------|----------|----------------------------|---------------------------|
| `np.arange(start, stop, step)` | 等差数列 | $a_n = a_1 + (n-1) \cdot d$ | [2, 4, 6, 8, 10]（d=2） |
| `np.linspace(start, stop, num)` | 等差数列 | $a_n = a_1 + (n-1) \cdot d$ | [1, 3.25, 5.5, 7.75, 10] |
| `np.logspace(start, stop, num, base=b)` | 等比数列 | $a_n = a_1 \cdot r^{n-1}$ | [1, 2, 4, 8]（r=2）     |

- **等差数列**：公差 $d$ 固定。
- **等比数列**：公比 $r$ 固定。

In [137]:
# 特殊矩阵的构造
# 单位矩阵:主对角线上的元素为1，其余元素为0的方阵
arr =  np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [142]:
# 对角矩阵：主对角线上是非0的数字，其他数字为0
arr = np.diag([5, 2, 3, 4])
print(arr)

[[5 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [149]:
# 随机数的生成
# 生成(0-1)之间的随机浮点数，均匀分布
arr = np.random.rand(2, 3)
print(arr)

[[0.10984444 0.12535211 0.30583586]
 [0.70315948 0.42898139 0.16679615]]


In [157]:
# 生成指定范围区间随机浮点数
arr = np.random.uniform(3, 6, (2, 3))  # 开始，结束，(行，列)
print(arr)

[[5.78406973 4.61439031 3.2388872 ]
 [3.5833545  3.05822414 3.43089517]]


In [194]:
# 生成指定范围区间随机整数
arr = np.random.randint(3, 30, (3, 3))  # 开始，结束，(行，列)
print(arr)

[[13 10  3]
 [18 18 15]
 [10 24 13]]


In [ ]:
# 生成随机数列正态分布
# 两边小，中间大
arr = np.random.randn(2, 3)
print(arr)

[[ 0.2725828  -0.57475265  1.0077521 ]
 [-1.07404037 -0.800923    1.14955783]]


In [233]:
# 随机种子
np.random.seed(2) 
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[9 9 7 3 9]
 [8 3 2 6 5]]


### 4 ndarray 的数据类型
- 布尔类型 bool（对错）
- 整数类型 int uint
- 浮点数 float
- 复数 complex

In [242]:
arr = np.array([1, 0, 2, 0], dtype=np.bool)  # 非0为True，0为False
print(arr)

[ True False  True False]


In [330]:
# 索引(标注数组元素的位置的数字）与切片 
arr = np.random.randint(1, 100, 30)
print(arr)
print(arr[0])  # 第一个元素
print(arr[:])  # 所有元素
print(arr[2:5])  # 第三到第五个元素，左包右不包 n
print(arr[slice(2, 5, 3)])  # 第三到第五个元素，左包右不包,隔3切。一个
print(arr[arr > 10])  # 布尔索引，通过布尔条件筛选，对应位置为True的元素会被选出
print(arr[(arr > 10) & (arr < 50)])  # 多条件筛选

[74 67 85 99 52 34  9 72 53 33 74 88 68 30 74 30 51 71  3 87 18 69 43 28
 69 17 23 57 42 32]
74
[74 67 85 99 52 34  9 72 53 33 74 88 68 30 74 30 51 71  3 87 18 69 43 28
 69 17 23 57 42 32]
[85 99 52]
[85]
[74 67 85 99 52 34 72 53 33 74 88 68 30 74 30 51 71 87 18 69 43 28 69 17
 23 57 42 32]
[34 33 30 30 18 43 28 17 23 42 32]


In [397]:
arr = np.random.randint(1, 100, (4, 8))
print(arr)
print(arr[(1, 3)])  # 索引
print(arr[1, :])  
print(arr[2][arr[2] > 50])
print(arr[:, 2])

[[61 38 53 15 34  9 52 48]
 [53  8 56 78 87 71 68 33]
 [92 54 41 80  4 95 10 61]
 [94 77 19 71 67 40 17 74]]
78
[53  8 56 78 87 71 68 33]
[92 54 80 95 61]
[53 56 41 19]


In [436]:
# ndarray 数组的运算
arr = np.array([1, 2, 3])
arr1 = np.array([4, 5, 6])
print(arr + arr1)  # 加减乘除一一对应位置运算

# ps: 列表
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)  # 列表相加是拼接，不是对应位置相加
for i in range(len(list1)):  
    list1[i] = list1[i] + list2[i]
print(list1)

[5 7 9]
[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [439]:
# ndarray 多维数组的运算
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1 = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(arr + arr1)

[[ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [443]:
# 广播机制
# 同一维度（行/列）相同或、1
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
print(a + b)
'''
a [1,2,3 
b
4
5
6。
'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [21]:
#矩阵运算
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a*b)
'''
a: 1 2 3
   4 5 6
   7 8 9
b: 4 5 6
   7 8 9
   1 2 3
'''
#不是矩阵乘法，矩阵乘法要用到dot
#矩阵乘法
c = np.dot(a,b)
print(c)
print(a @ b) #矩阵乘法

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]



### numpy 常用指令
#### 基本数学函数

In [31]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(arr)

3.0
[1. 2. 3.]
[ 1 25 81]


In [46]:
# 计算指数
print(np.exp(1))  # 以 e 为底

2.718281828459045


In [43]:
# 计算自然对数  lnx 
np.log(2.718281828459045)

np.float64(1.0)

In [60]:
# 计算正弦值，余弦
print(np.sin(np.pi / 2))  # sin 90度 =1
print(np.cos(0))        # cos 0度 =1
print(np.cos(np.pi))  # cos 180度 =-1

1.0
1.0
-1.0


In [65]:
# 计算绝对值
arr = np.array([-1, 1, -2, 2])
print(np.abs(arr)) 

[1 1 2 2]


In [80]:
# 计算 a 的 b 次幂
print(np.power(arr, 2))  
print(np.power(2, 3))  # 2的3次幂

[1 1 4 4]
8


In [107]:
# 四舍五入
print(np.round([8.1, 9.6, 4.5, 4.6]))  # 4.5变成4了

[ 8. 10.  4.  5.]


In [110]:
# 向上取整，向下取整
arr = np.array([1.6, 25, 1, 81, 7])
print(np.ceil(arr))  # 向上取整
print(np.floor(arr))  # 向下取整

[ 2. 25.  1. 81.  7.]
[ 1. 25.  1. 81.  7.]


In [116]:
# 检测缺失值 NaN
np.isnan([1, 2, 3, np.nan, 5])  # np.nan 缺失值

array([False, False, False,  True, False])

### 统计函数
- 求和，计算平均值，中位数，标准差，方差 
- 查找最大值，最小值，计算分位数，累计和，累计差

In [136]:
arr = np.random.randint(1, 20, 8)
print(arr)
print(np.sum(arr))  # 求和

[11 17  6 13  6  8  9  6]
76


In [142]:
# 计算平均值
print(np.mean(arr))

9.5


In [151]:
# 中位数
print(np.median([1, 2, 3]))  # 奇数取中间位置数
print(np.median([1, 2, 3, 4]))  # 偶数取中间两个数的平均值

2.0
2.5


In [158]:
# 计算方差，标准差
print(np.var(arr))
print(np.std(arr))

13.75
3.7080992435478315


In [170]:
# 计算最值
print(arr)

print(np.min(arr), np.argmin(arr))  # 最小值，最小值的位置(索引,从0开始)
 
print(np.max(arr), np.argmax(arr))  # 最大值，最大值的位置(索引)

[11 17  6 13  6  8  9  6]
6 2
17 1


In [174]:
# 分位数，百分之多少的数据小于它
print(arr)
print(np.percentile(arr, 50))  # 中位数
print(np.percentile(arr, 25))  # 25分位数
print(np.percentile(arr, 75))  # 75分位数
print(np.percentile(arr, 0))  # 最小值 

[11 17  6 13  6  8  9  6]
8.5
6.0
11.5
6.0


In [183]:
# 累计和，累计积
arr = np.array([1, 2, 3])
print(np.cumsum(arr))  # 累计和
print(np.cumprod(arr))  # 累计积

[1 3 6]
[1 2 6]


## 比较函数
- 比较是否大于、等于、小于
- 逻辑，与、或、非
- 检查数组中是否有一个 True，是否所有的都是 True，自定义条件

In [197]:
# 是否大于
print(np.greater([3, 4, 5, 6, 7], 4)) 
# 是否小于 np.less
print(np.less([3, 4, 5, 6, 7], 4))
# 是否等于
print(np.equal([3, 4, 5, 6, 7], 4)) 

[False False  True  True  True]
[ True False False False False]
[False  True False False False]


In [206]:
# 与
print(np.logical_and([0, 1, 0], [0, 1, 1]))  # 两个都为真才 True
# 或
print(np.logical_or([0, 1, 0], [0, 1, 1]))  # 有一个为真就 True
# 非
print(np.logical_not([1, 0]))  # 取反 

[False  True False]
[False  True  True]
[False  True]


In [231]:

print(np.any([0, 0, 0, 1, 0]))  # 一个是 True 就 True
print(np.any([0, 0, 0, 0, 0, 0, 0]))
print(np.all([1, 1, 1, 1, 1, 1, 0]))  # 所有都是 True 才 True
print(np.all([1, 1, 1, 1]))  # 所有都是 True 才 True

True
False
False
True


In [236]:
# 自定义条件 where
# np.where(条件，符合取，不符合取)
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.where(arr > 3, arr, 0))  # 大于 3 取 arr 的值，否则取 0

[0 0 0 4 5 6]


In [239]:
# 举例
score = np.random.randint(0, 100, 32)  # 生成 32 个学生 0-100 的随机整数分数
print(score)
print(np.where(score >= 60, '及格', '不及格'))

[ 4  4 97  1 34 17 61 39 13 65 84 42 22 20 70 36 76 45 46 87 88 10 35 74
 92 73 61  0 48 75 67 62]
['不及格' '不及格' '及格' '不及格' '不及格' '不及格' '及格' '不及格' '不及格' '及格' '及格' '不及格' '不及格'
 '不及格' '及格' '不及格' '及格' '不及格' '不及格' '及格' '及格' '不及格' '不及格' '及格' '及格' '及格'
 '及格' '不及格' '不及格' '及格' '及格' '及格']


In [243]:
# 三个条件
score = np.random.randint(0, 100, 32)  # 生成 32 个学生 0-100 的随机整数分数
print(score)
print(np.where(score < 60, '不及格',
               np.where(score < 85, '良好', '优秀')))  # 嵌套 

[89 17 59 85 49 33 69 31 92  2  1 50 27 72 61 60 62 61 64 91  4 75  4 62
  1 48 65 62 50 46 67 68]
['优秀' '不及格' '不及格' '优秀' '不及格' '不及格' '良好' '不及格' '优秀' '不及格' '不及格' '不及格' '不及格'
 '良好' '良好' '良好' '良好' '良好' '良好' '优秀' '不及格' '良好' '不及格' '良好' '不及格' '不及格' '良好'
 '良好' '不及格' '不及格' '良好' '良好']


In [265]:
# 排序函数
np.random.seed(0)
arr = np.random.randint(1, 100, 20)

print(arr)

print(np.sort(arr))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]


In [267]:
# 去重函数
arr = np.unique(arr)  # 去重加排序 
print(arr)

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [270]:
# 数组拼接

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))  # 拼接
print(arr3)

[1 2 3 4 5 6]


In [286]:
# 数组分割
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


## 练习


In [333]:
#温度数据分析
#某城市一周最高温度:[28,30,29,31,32,30,29]
#计算平均、最高、最低气温
#找出超过30度的天数
import numpy as np
temp = np.array([28,30,29,31,32,30,29])

print("{:.3f}".format(np.mean(temp)))#平均温度保留三位小数

print(np.max(temp))#最高温度

print(np.min(temp))#最低温度

print(np.sum(temp>30))#超过30度的天数



29.857
32
28
2


In [351]:
#成绩数据分析
arr = np.array([85,90,78,92,88])

#平均分
print(np.mean(arr))
#中位数
print(np.median(arr))
#标准差
print(np.std(arr))
#建设满分是10分

print(arr/10)


86.6
88.0
4.882622246293481
[8.5 9.  7.8 9.2 8.8]


In [427]:
np.random.seed(0)

arr = np.random.randint(0,10,(3,4))
print(arr)
 

for i in range(0,3):
    print(np.max(arr[i][:]),np.min(arr[i][:]),sep = ',')

for i in range(0,3):
    print(np.where(arr[i] %2 == 0,arr[i],-1))

        
 


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
5,0
9,3
7,2
[-1  0 -1 -1]
[-1 -1 -1 -1]
[ 2  4 -1  6]


In [529]:
arr = np.arange(1,13) #1到12的数组整数

print(arr) 

arr = np.reshape(arr,(3,4))#转型

print(arr)

print(np.sum(arr,axis = 1)) #每行的和

print(np.average(arr,axis = 0)) #每列的平均值 

print(np.reshape(arr,(-1))) #展平




[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [538]:
np.random.seed(1)

arr = np.random.randint(0,20,(5,5))

print(arr)

print(np.where(arr > 10,0,arr))
 

[[ 5 11 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 13  6]
 [18  5 18 11 10]
 [14 18  4  9 17]]
[[ 5  0  0  8  9]
 [ 0  5  0  0  0]
 [ 1  0  7  0  6]
 [ 0  5  0  0 10]
 [ 0  0  4  9  0]]


In [557]:
sell = np.array([120,135,110,125,130,140])

print(np.sum(sell)) #总和

print(np.mean(sell)) #平均值

print(np.var(sell)) #方差

print(np.max(sell)) #最大值
print(np.argmax(sell)+ 1) #最大值索引

print(np.min(sell)) #最小值. 
print(np.argmin(sell)+1) #最小值索引

760
126.66666666666667
97.22222222222223
140
6
110


In [590]:
#横着拼，竖着拼

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6,])

print(np.concatenate([arr1,arr2]))

arr3 = np.concatenate([arr1,arr2])

print(np.reshape(arr3,(2,3))).   

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [626]:
#唯一数值

arr =  np.array([2,1,2,3,1,4,3])



#字典
count = {}
for i in arr:
    count[i] = count.get(i,0) + 1

print("一共",len(count),"个唯一值")

#numpy
values,count= np.unique(arr,return_counts = True) #返回计数 return_counts
print("统计完成！共", len(values), "个唯一值")

一共 4 个唯一值
统计完成！共 4 个唯一值


In [ ]:
# 综合题：计算利润
# 五天销售额 [20, 25, 22, 30, 28]
# 五天成本 [15, 18, 16, 22, 20]
# 计算利润、平均利润、利润标准差、利润最高的天数
import numpy as np

# 销售额和成本
sale = np.array([20, 25, 22, 30, 28])
cost = np.array([15, 18, 16, 22, 20])

# 计算利润
profit = sale - cost
print("每日利润:", profit)

# 平均利润
average_profit = np.average(profit)
print("平均利润:", average_profit)

# 利润标准差
std_profit = np.std(profit)
print("利润标准差:", std_profit)

# 利润最高的天数
max_profit_day = np.argmax(profit) + 1  # 天数从 1 开始
print("利润最高的天数: 第", max_profit_day, "天")

[5 7 6 8 8]
6.8
1.16619037896906
3
