#  ndarray 
## ndarray 特性
### 多维性质

In [4]:
import numpy as np #创建0纬度ndarray数组
arr = np.array(5)
print(arr)
print('arr的维度:',arr.ndim)#看维度

5
arr的维度: 0


In [32]:
 #创建1纬度ndarray数组
arr = np.array([1,2,3])
print(arr)
print('arr的维度:',arr.ndim)#看维度 number of dimensions

[1 2 3]
arr的维度: 1


In [6]:
 #创建2纬度ndarray数组
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('arr的维度:',arr.ndim)#看维度 number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度: 2


### 同质性

In [13]:

arr = np.array([1,1.5])#不同数据类型会被转换 
print(arr)

[1.  1.5]


## 2.2 ndarray的属性

In [17]:
arr = np.array(1)
print(arr)
print('数组的形状',arr.shape)

1
数组的形状 ()


In [20]:
arr = np.array([1,2,3])
print(arr)
print('数组的形状',arr.shape)

[1 2 3]
数组的形状 (3,)


In [30]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状',arr.shape)  
print(arr.size) #数组的大小 元素个数

[[1 2 3]
 [4 5 6]]
数组的形状 (2, 3)
6


In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print('数组的形状',arr.shape)  
print(arr.size) #数组的大小 元素个数
print(arr.dtype) #数组的数据类型
print(arr.T) #数组的转置


[[1 2 3]
 [4 5 6]
 [7 8 9]]
数组的形状 (3, 3)
9
int64
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## ndarray数组创建

In [43]:
list = [1,2,3]
arr = np.array(list,dtype = np.float64)
print(arr)
print(arr.ndim)#维度

[1. 2. 3.]
1


In [47]:
#copy
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


In [51]:
#预定义形状
#全0 全1 未初始化 固定值
#全0
arr = np.zeros((2,3),dtype = np.int64)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [56]:
arr = np.zeros((2,),dtype = np.int64)
print(arr)

[0 0]


In [58]:
arr = np.ones((5,8),dtype = np.int64)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [83]:
#未初始化
arr = np.empty((5,8),dtype = np.int64)
print(arr). 

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [84]:
#其他预定义填充
arr = np.full((9,9),2021,dtype = np.int64)
print(arr)

[[2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]
 [2021 2021 2021 2021 2021 2021 2021 2021 2021]]


In [89]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026 2026

In [95]:
#等差数列
arr = np.arange(2,11,2)#不包含最后一个 11
print(arr)

[ 2  4  6  8 10]


In [111]:
#等间隔数列
arr = np.linspace(1,10  ,5,dtype = int)#把前后长度均分成3个等间隔的数
print(arr)
 

[ 1  3  5  7 10]


In [132]:
#对数间隔
arr = np.logspace(1,10,10,base = 2)#base:以谁为底，（开始，结束，个数）
print(arr)
 

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


## NumPy 函数与数学公式对应

| 函数          | 数学类型     | 公式/描述                  | 示例输出                  |
|---------------|--------------|----------------------------|---------------------------|
| `np.arange(start, stop, step)` | 等差数列    | a_n = a_1 + (n-1)*d       | [2, 4, 6, 8, 10]（d=2） |
| `np.linspace(start, stop, num)` | 等差数列    | a_n = a_1 + (n-1)*d       | [1, 3.25, 5.5, 7.75, 10]（d自动算） |
| `np.logspace(start, stop, num, base=b)` | 等比数列    | a_n = a_1 * r^(n-1)       | [1, 2, 4, 8]（r=2）     |

- **等差数列**：公差 d 固定。
- **等比数列**：公比 r 固定。

In [137]:
#特殊矩阵的构造
#单位矩阵:主对角线上的元素为1，其余元素为0的方阵
arr =  np.eye(3,4,dtype = int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [142]:
#对角矩阵：主对角线上是非0的数字，其他数字为0
arr = np.diag([5,2,3,4])
print(arr)

[[5 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [149]:
#随机数的生成
#生成(0-1)之间的随机浮点数，均匀分布
arr = np.random.rand(2,3)
print(arr)

[[0.10984444 0.12535211 0.30583586]
 [0.70315948 0.42898139 0.16679615]]


In [157]:
#生成指定范围区间随机浮点数
arr = np.random.uniform(3,6,(2,3))#开始，结束，(行，列)
print(arr)

[[5.78406973 4.61439031 3.2388872 ]
 [3.5833545  3.05822414 3.43089517]]


In [194]:
#生成指定范围区间随机整数
arr = np.random.randint(3,30,(3,3))#开始，结束，(行，列)
print(arr)

[[13 10  3]
 [18 18 15]
 [10 24 13]]


In [213]:
#生成随机数列正态分布
#两边小，中间大
arr = np.random.randn(2,3)
print(arr)

[[ 0.2725828  -0.57475265  1.0077521 ]
 [-1.07404037 -0.800923    1.14955783]]


In [233]:
#随机种子
np.random.seed(2) 
arr = np.random.randint(1,10,(2,5))
print(arr)

[[9 9 7 3 9]
 [8 3 2 6 5]]


### 4 ndarray的数据类型
布尔类型 bool（对错）
整数类型 int uint
浮点数 float
复数 complex

In [242]:
arr = np.array([1,0,2,0],dtype = np.bool)  #非0为True，0为False
print(arr)

[ True False  True False]


In [330]:
#索引(标注数组元素的位置的数字）与切片 
arr = np.random.randint(1,100,30)
print(arr)
print(arr[0])#第一个元素
print(arr[:])#所有元素
print(arr[2:5])#第三到第五个元素，左包右不包 n
print(arr[slice(2,5,3)])#第三到第五个元素，左包右不包,隔3切。一个
print(arr[arr>10])#布尔索引，通过布尔条件筛选，对应位置为True的元素会被选出
print(arr[(arr>10) & (arr<50)])#多条件筛选

[74 67 85 99 52 34  9 72 53 33 74 88 68 30 74 30 51 71  3 87 18 69 43 28
 69 17 23 57 42 32]
74
[74 67 85 99 52 34  9 72 53 33 74 88 68 30 74 30 51 71  3 87 18 69 43 28
 69 17 23 57 42 32]
[85 99 52]
[85]
[74 67 85 99 52 34 72 53 33 74 88 68 30 74 30 51 71 87 18 69 43 28 69 17
 23 57 42 32]
[34 33 30 30 18 43 28 17 23 42 32]


In [397]:
arr = np.random.randint(1,100,(4,8))
print(arr)
print(arr[(1,3)])#索引
print(arr[1,:])  
print(arr[2] [arr[2]>50])
print(arr[:,2])

[[61 38 53 15 34  9 52 48]
 [53  8 56 78 87 71 68 33]
 [92 54 41 80  4 95 10 61]
 [94 77 19 71 67 40 17 74]]
78
[53  8 56 78 87 71 68 33]
[92 54 80 95 61]
[53 56 41 19]


In [ ]:
import numpy as np

#ndarray数组的运算
arr = np.array([1,2,3])
arr1 = np.array([4,5,6])
print(arr + arr1)#加减乘除一一对应位置运算

#ps:列表
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)#列表相加是拼接，不是对应位置相加

[5 7 9]
